name: flutter_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7  # Correctamente colocado fuera del bloque flutter
  http: ^1.2.2  # Actualizado a la versi칩n m치s reciente
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Actualizado a la versi칩n m치s reciente

flutter:
  uses-material-design: true


